#!/usr/bin/env bash
#
# by jsuereth and paulp

gitignore="$(dirname $0)/.gitignore"
bootdir="$(dirname $0)/.boot"
sbtjar="${bootdir}/sbt-launch.jar"
sbtversion=0.10.1
sbturl="http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-tools.sbt/sbt-launch/$sbtversion/sbt-launch.jar"

if [[ ! -d "$bootdir" ]]; then
  echo "Creating .boot directory for xsbt"
  pushd $(dirname $0)
  mkdir $bootdir
  popd
fi

if [[ ! -f "$gitignore" ]]; then
  echo "Creating .gitignore containing:"
  # TODO - if file exists, just add .boot to ignore if it's not there.
  cat > "$gitignore" <<EOM
.gitignore
.boot
EOM
  cat "$gitignore"
  echo ""
elif ! grep -Fq ".boot" "$gitignore"; then
  echo "Appending .boot to .gitignore."
  echo ".boot" >> "$gitignore"
fi

# TODO - Check version of SBT launch jar in some kind of tag file so we can pull new versions when needed.
if [[ ! -f "$sbtjar" ]]; then
  echo "Downloading sbt version $sbtversion to $sbtjar ..."
  echo ""
  if [[ ! `which curl` -eq 0 ]]; then
    curl --silent "$sbturl" > "$sbtjar"
  elif [[ ! `which wget` -eq 0 ]]; then
    pushd $bootdir
    wget $sbturl 
    popd
  else
   echo "No means of downloading sbt-launch.jar found.   Either:"
   echo " * install curl"
   echo " * install wget"
   echo " * manually download $sbturl and place at $sbtjar"
   echo ""
  fi
fi
java $JAVA_OPTS \
  -XX:+CMSClassUnloadingEnabled \
  -XX:MaxPermSize=256m \
  -Xmx3g -Xss2M \
  -jar "$sbtjar" "$@"
