#!/usr/bin/env bash
#

# TODO - Version the sbt-launch jar and hide somewhere less obvious than the
# current directory!
if [ ! -e $(dirname $0)/sbt-launch.jar ]; then
  pushd $(dirname $0)
  wget http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-tools.sbt/sbt-launch/0.10.0/sbt-launch.jar 
  popd
fi
java $JAVA_OPTS \
  -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256m -Xmx3g -Xss2M \
  -jar $(dirname $0)/sbt-launch*.jar "$@"
